services:
  db_admins:
    container_name: db_admins
    image: mongo:6.0
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - my-network
    ports:
      - 27017:27017

  admins:
    container_name: admins
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - DB_URI=mongodb://db_admins:27017
      - DB_NAME=backoffice
      - GATEWAY_TOKEN=gateway-token
      - GATEWAY_URL=http://gateway:3000
    networks:
      - my-network
    ports:
      - 3004:3004
    depends_on:
      - db_admins

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
    networks:
      - my-network
    ports:
      - 9095:9090

  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
    - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - my-network
    ports:
      - 3006:3000

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - my-network
    ports:
      - 9094:9094

volumes:
  mongo_data:
    name: db_admins

networks:
  my-network:
    name: classconnect_net
    external: true
