version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - monitor-net

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3004:3004"
    networks:
      - monitor-net
    environment:
      - DB_URI=mongodb://mongo:27017
      - DB_NAME=backoffice
    depends_on:
      - mongo

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:5173" 
    networks:
      - monitor-net

  prometheus-main:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
    ports:
      - "9095:9090"
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    ports:
      - "3006:3000"
    volumes:
    - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - monitor-net

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9094:9094"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - monitor-net

volumes:
  mongo_data:

networks:
  monitor-net:
    external: 
      name: classconnect_net