services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    networks:
      - my-network
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  admins:
    container_name: admins
    build: ./backend
    networks:
      - my-network
    ports:
      - 3004:3004
    environment:
      - DB_URI=mongodb://mongo:27017
      - DB_NAME=backoffice
      - ADMIN_TOKEN=admin-token
      - GATEWAY_URL=http://gateway:3000
    depends_on:
      - mongo

  # prometheus:
  #   image: prom/prometheus
  #   volumes:
  #     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"

  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - "3006:3006"


volumes:
  mongo_data:

networks:
  my-network:
    name: classconnect_net
    external: true
