services:
  db_admins:
    container_name: db_admins
    image: mongo:6.0
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - my-network
    ports:
      - 27017:27017

  admins:
    container_name: admins
    build: .
    environment:
      - DB_URI=mongodb://db_admins:27017
      - DB_NAME=backoffice
      - GATEWAY_TOKEN=gateway-token
      - GATEWAY_URL=http://gateway:3000
    networks:
      - my-network
    ports:
      - 3004:3004
    depends_on:
      - db_admins

volumes:
  mongo_data:
    name: db_admins

networks:
  my-network:
    name: classconnect_net
    external: true
