name: CI

on:
  push:
    branches: [main, actions]
  pull_request:
    branches: [main, actions]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: testsecret
      PORT: 3004

    strategy:
      matrix:
        python-version: [3.13]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi

      - name: Run tests
        run: |
          pytest --cov=backend --cov-branch --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-coverage
